# disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "B's Garden City"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2 2006"
  logo = "seedling-animated.gif"
  secondaryLogo = "leaf-animated.gif"
  description = "BinaryDigit.city"
  copyright = " 2025 BinaryDigit"

[params.author]
   name = "BinaryDigit"
   email = "hi@binarydigit.city"
   image = "BinaryDigit.jpg"
   imageQuality = 100
   headline = "A creative spirit stuck in tech burnout"
   bio = "A creative spirit stuck in tech burnout"
   links = [
          { envelope = "https://letterbird.co/binarydigit" },
          { link = "https://links.binarydigit.city" },
          { mastodon = "https://social.lol/@binarydigit" },
          { github = "https://github.com/bndgt"},
          { twitch = "https://twitch.tv/binarydigit" },
          { ko-fi = "https://ko-fi.com/binarydigit" },
]
