name: Deploy to Neocities
on:
  # Build on pushes to the main branch only
  push:
    branches:
      - main

concurrency: 
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and deploy Hugo site
    runs-on: ubuntu-latest
    steps:
      # Install Hugo in the runner
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.139.0'
          extended: true

      # Check out the source for the site
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Build the site with Hugo
      - name: Build with Hugo
        run: hugo --minify
      
      # Push the rendered site to Neocities and clean up any orphaned files

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_TOKEN }}
          cleanup: true
          dist_dir: public