- name: Deploy to Surfer
  uses: addnab/docker-run-action@v3
  with:
    image: git.9wd.eu/9wd/surfer-action:latest
    run: |
    surfer --version
    surfer put --token $SURFER_KEY --server test.binarydigit.media public/* /
