- name: SFTP Upload
uses: Dylan700/sftp-upload-action@v1.2.3
  with:
    server: ${{secrets.server}}
    username: ${{secrets.username}}
    password: ${{secrets.password}}
    port: ${{secrets.port}}
    uploads: /public/ => /var/www/my_webapp/www/