name: Deploy via SFTP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: deploy
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: './public/'
          remoteDir: './var/www/my_webapp/www/'
          reverse: true
          ignoreFile: '.lftp_ignore'
          options: '--verbose'