stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  image: monachus/hugo
  stage: build
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - main

deploy:
  image: node:latest
  stage: deploy
  script:
  - npm -g install cloudron-surfer
  - surfer put --token $SURFER_KEY --server test.binarydigit.media public/* /

  only:
  - main
